"""staff zone assignments

Revision ID: 780b0745eefd
Revises: a5c9575eb078
Create Date: 2026-09-12 13:22:02.764072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '780b0745eefd'
down_revision: Union[str, Sequence[str], None] = 'a5c9575eb078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('zone_key', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_staff_zone_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_zone')),
    sa.UniqueConstraint('user_id', 'zone_key', name='uq_staff_zone_user_id')
    )
    with op.batch_alter_table('staff_zone', schema=None) as batch_op:
        batch_op.create_index('ix_staff_zone_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_zone', schema=None) as batch_op:
        batch_op.drop_index('ix_staff_zone_user')

    op.drop_table('staff_zone')
    # ### end Alembic commands ###
