"""initial schema

Revision ID: a5c9575eb078
Revises: 
Create Date: 2026-09-12 11:25:00.645086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c9575eb078'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day', sa.String(length=16), nullable=False),
    sa.Column('time_slot', sa.String(length=32), nullable=False),
    sa.Column('start_min', sa.Integer(), nullable=False),
    sa.Column('end_min', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=64), nullable=False),
    sa.Column('room_type', sa.String(length=32), nullable=False),
    sa.Column('course_code', sa.String(length=64), nullable=False),
    sa.Column('course_title', sa.String(length=255), nullable=True),
    sa.Column('section', sa.String(length=32), nullable=False),
    sa.Column('batch', sa.String(length=32), nullable=False),
    sa.Column('teacher_initial', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'LATE', 'MISSED', 'NOT_CHECKED', 'MAKEUP_SCHEDULED', 'MAKEUP_COMPLETED', 'ONLINE_PENDING', 'ONLINE_APPROVED', 'ONLINE_REJECTED', 'CANCELLED', name='classstatus', native_enum=False), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_makeup', sa.Boolean(), nullable=False),
    sa.Column('makeup_id', sa.Integer(), nullable=True),
    sa.Column('teacher_response', sa.Enum('CONFIRMED', 'DISPUTED', name='teacherresponse', native_enum=False), nullable=True),
    sa.Column('response_note', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['makeup_id'], ['makeup_class.id'], name=op.f('fk_class_instance_makeup_id_makeup_class'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], name=op.f('fk_class_instance_semester_id_semester'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['class_session.id'], name=op.f('fk_class_instance_session_id_class_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_instance')),
    sa.UniqueConstraint('session_id', 'date', name='uq_class_instance_session_date')
    )
    with op.batch_alter_table('class_instance', schema=None) as batch_op:
        batch_op.create_index('ix_instance_date_room', ['date', 'time_slot', 'room'], unique=False)
        batch_op.create_index('ix_instance_date_slot', ['date', 'time_slot'], unique=False)
        batch_op.create_index('ix_instance_section_date', ['section', 'date', 'time_slot'], unique=False)
        batch_op.create_index('ix_instance_status_date', ['status', 'date'], unique=False)
        batch_op.create_index('ix_instance_teacher_date', ['teacher_initial', 'date'], unique=False)

    op.create_table('makeup_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_instance_id', sa.Integer(), nullable=False),
    sa.Column('teacher_initial', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.Enum('PHYSICAL', 'ONLINE', name='makeupmode', native_enum=False), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_slot', sa.String(length=32), nullable=False),
    sa.Column('room', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', name='makeupstatus', native_enum=False), nullable=False),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_instance_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_instance_id'], ['class_instance.id'], name=op.f('fk_makeup_class_created_instance_id_class_instance'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['user.id'], name=op.f('fk_makeup_class_decided_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['original_instance_id'], ['class_instance.id'], name=op.f('fk_makeup_class_original_instance_id_class_instance'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_makeup_class'))
    )
    with op.batch_alter_table('makeup_class', schema=None) as batch_op:
        batch_op.create_index('ix_makeup_original', ['original_instance_id'], unique=False)
        batch_op.create_index('ix_makeup_status', ['status'], unique=False)
        batch_op.create_index('ix_makeup_teacher', ['teacher_initial'], unique=False)

    op.create_table('routine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=16), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('semester', sa.String(length=64), nullable=True),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routine')),
    sa.UniqueConstraint('department', 'version', name='uq_routine_department_version')
    )
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.create_index('ix_routine_department_active', ['department', 'is_active'], unique=False)

    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initial', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('office_room', sa.String(length=64), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher'))
    )
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.create_index('ix_teacher_department', ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_initial'), ['initial'], unique=True)

    op.create_table('class_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=16), nullable=False),
    sa.Column('time_slot', sa.String(length=32), nullable=False),
    sa.Column('room', sa.String(length=64), nullable=False),
    sa.Column('room_type', sa.String(length=32), nullable=False),
    sa.Column('course_code', sa.String(length=64), nullable=False),
    sa.Column('course_title', sa.String(length=255), nullable=True),
    sa.Column('teacher', sa.String(length=16), nullable=False),
    sa.Column('batch', sa.String(length=32), nullable=False),
    sa.Column('section', sa.String(length=32), nullable=False),
    sa.Column('is_lab', sa.Boolean(), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('start_min', sa.Integer(), nullable=False),
    sa.Column('end_min', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.id'], name=op.f('fk_class_session_routine_id_routine'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_session'))
    )
    with op.batch_alter_table('class_session', schema=None) as batch_op:
        batch_op.create_index('ix_session_batch', ['routine_id', 'batch'], unique=False)
        batch_op.create_index('ix_session_day_slot', ['routine_id', 'day', 'time_slot'], unique=False)
        batch_op.create_index('ix_session_room_day_slot', ['routine_id', 'room', 'day', 'time_slot'], unique=False)
        batch_op.create_index('ix_session_teacher', ['routine_id', 'teacher'], unique=False)

    op.create_table('semester',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('department', sa.String(length=16), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.id'], name=op.f('fk_semester_routine_id_routine'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semester'))
    )
    with op.batch_alter_table('semester', schema=None) as batch_op:
        batch_op.create_index('ix_semester_department_active', ['department', 'is_active'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'HOD', 'STAFF', 'TEACHER', name='role', native_enum=False), nullable=False),
    sa.Column('teacher_initial', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_initial'], ['teacher.initial'], name=op.f('fk_user_teacher_initial_teacher'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index('ix_user_role', ['role'], unique=False)
        batch_op.create_index('ix_user_teacher_initial', ['teacher_initial'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], name=op.f('fk_audit_log_actor_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_actor', ['actor_id'], unique=False)
        batch_op.create_index('ix_audit_created', ['created_at'], unique=False)
        batch_op.create_index('ix_audit_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('check_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('checked_by_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.Enum('RUNNING', 'LATE', 'TEACHER_NOT_FOUND', name='checkoutcome', native_enum=False), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=True),
    sa.Column('late_minutes', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['checked_by_id'], ['user.id'], name=op.f('fk_check_record_checked_by_id_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['instance_id'], ['class_instance.id'], name=op.f('fk_check_record_instance_id_class_instance'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_check_record')),
    sa.UniqueConstraint('instance_id', name='uq_check_record_instance_id')
    )
    with op.batch_alter_table('check_record', schema=None) as batch_op:
        batch_op.create_index('ix_check_user_date', ['checked_by_id', 'checked_at'], unique=False)

    op.create_table('holiday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('HOLIDAY', 'EXAM', 'CLOSED', 'SPECIAL', name='daykind', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], name=op.f('fk_holiday_semester_id_semester'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holiday')),
    sa.UniqueConstraint('semester_id', 'date', name='uq_holiday_semester_date')
    )
    with op.batch_alter_table('holiday', schema=None) as batch_op:
        batch_op.create_index('ix_holiday_date', ['date'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('MISSED_CLASS', 'MAKEUP_REMINDER', 'ONLINE_REQUEST', 'ONLINE_DECISION', 'DISPUTE_RAISED', name='notificationkind', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_notification_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index('ix_notification_user_unread', ['user_id', 'read_at'], unique=False)

    op.create_table('setting',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_setting_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_setting'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setting')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_user_unread')

    op.drop_table('notification')
    with op.batch_alter_table('holiday', schema=None) as batch_op:
        batch_op.drop_index('ix_holiday_date')

    op.drop_table('holiday')
    with op.batch_alter_table('check_record', schema=None) as batch_op:
        batch_op.drop_index('ix_check_user_date')

    op.drop_table('check_record')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_entity')
        batch_op.drop_index('ix_audit_created')
        batch_op.drop_index('ix_audit_actor')

    op.drop_table('audit_log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_teacher_initial')
        batch_op.drop_index('ix_user_role')
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('semester', schema=None) as batch_op:
        batch_op.drop_index('ix_semester_department_active')

    op.drop_table('semester')
    with op.batch_alter_table('class_session', schema=None) as batch_op:
        batch_op.drop_index('ix_session_teacher')
        batch_op.drop_index('ix_session_room_day_slot')
        batch_op.drop_index('ix_session_day_slot')
        batch_op.drop_index('ix_session_batch')

    op.drop_table('class_session')
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_initial'))
        batch_op.drop_index('ix_teacher_department')

    op.drop_table('teacher')
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.drop_index('ix_routine_department_active')

    op.drop_table('routine')
    with op.batch_alter_table('makeup_class', schema=None) as batch_op:
        batch_op.drop_index('ix_makeup_teacher')
        batch_op.drop_index('ix_makeup_status')
        batch_op.drop_index('ix_makeup_original')

    op.drop_table('makeup_class')
    with op.batch_alter_table('class_instance', schema=None) as batch_op:
        batch_op.drop_index('ix_instance_teacher_date')
        batch_op.drop_index('ix_instance_status_date')
        batch_op.drop_index('ix_instance_section_date')
        batch_op.drop_index('ix_instance_date_slot')
        batch_op.drop_index('ix_instance_date_room')

    op.drop_table('class_instance')
    # ### end Alembic commands ###
